# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_ana_logical <- function(x_, terms, any_len, ignore_spaces, ignore_case) {
    .Call('_anagrams_get_ana_logical', PACKAGE = 'anagrams', x_, terms, any_len, ignore_spaces, ignore_case)
}

get_ana_character <- function(x_, terms, any_len, ignore_spaces, ignore_case) {
    .Call('_anagrams_get_ana_character', PACKAGE = 'anagrams', x_, terms, any_len, ignore_spaces, ignore_case)
}

