# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_is_anagram <- function(x, terms, value, any_len) {
    .Call('_anagrams_cpp_is_anagram', PACKAGE = 'anagrams', x, terms, value, any_len)
}

